schemaVersion: 2.1.0
metadata:
  name: java-maven-quarkus-lombok
components:
  - name: tools
    container:
      args:
        - sh
        - '-c'
        - '${PLUGIN_REMOTE_ENDPOINT_EXECUTABLE}'
      endpoints:
        - exposure: none
          name: debug
          protocol: tcp
          targetPort: 5005
        - exposure: public
          name: blog-posts-endpoint
          path: /blog/posts
          protocol: http
          targetPort: 8080
      env:
        - name: QUARKUS_HTTP_HOST
          value: 0.0.0.0
      image: 'quay.io/devfile/universal-developer-image:ubi8-latest'
      memoryLimit: 4G
      mountSources: true
      sourceMapping: /projects
      volumeMounts:
        - name: m2
          path: /home/user/.m2
  - container:
      args:
        - '-f'
        - /dev/null
      command:
        - tail
      image: registry.access.redhat.com/ubi8/ubi-minimal
      memoryLimit: 64M
      mountSources: true
      sourceMapping: /projects
    name: ubi-minimal
  - name: m2
    volume:
      size: 1G
# commands:
#   - exec:
#       commandLine: mvn package
#       component: tools
#       group:
#         isDefault: true
#         kind: build
#       workingDir: '${PROJECT_SOURCE}/getting-started'
#     id: package
#   - exec:
#       commandLine: mvn package -Dnative -Dmaven.test.skip -Dquarkus.native.native-image-xmx=2G
#       component: tools
#       group:
#         kind: build
#       label: Package Native
#       workingDir: '${PROJECT_SOURCE}/getting-started'
#     id: package-native
#   - exec:
#       commandLine: 'mvn compile quarkus:dev'
#       component: tools
#       group:
#         isDefault: true
#         kind: run
#       label: Start Development mode (Hot reload + debug)
#       workingDir: '${PROJECT_SOURCE}/getting-started'
#     id: start-dev
#   - exec:
#       commandLine: ./getting-started-1.0.0-SNAPSHOT-runner
#       component: ubi-minimal
#       group:
#         kind: run
#       label: Start Native
#       workingDir: '${PROJECT_SOURCE}/getting-started/target'
#     id: start-native