
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default_view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: default
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: devspaces-quarkus-crud-demo
spec:
  lookupPolicy:
    local: false
  tags:
    - name: java11-latest
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/rafaeltuelho/devspaces-quarkus-crud-demo:java11-latest'
      importPolicy: {}
      referencePolicy:
        type: Source
      importPolicy: { }
      referencePolicy:
        type: Source
